import { Roboto_Mono } from 'next/font/google'
import NavBar from '@/components/navBar/NavBar'
import './globals.css'

const inter = Roboto_Mono({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavBar/>
        {children}
        </body>
    </html>
  )
}
